encoding: utf-8
lang: ja
title: Banana Systems
email: contact@banana-systems.com
description: "Banana Systems 株式会社"
google_analytics: UA-50664-11

theme: minima

# Build settings
markdown: kramdown

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - docker-compose.yml
